// Generated by gencpp from file determinant/determineResponse.msg
// DO NOT EDIT!


#ifndef DETERMINANT_MESSAGE_DETERMINERESPONSE_H
#define DETERMINANT_MESSAGE_DETERMINERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace determinant
{
template <class ContainerAllocator>
struct determineResponse_
{
  typedef determineResponse_<ContainerAllocator> Type;

  determineResponse_()
    : result(0.0)  {
    }
  determineResponse_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef double _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::determinant::determineResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::determinant::determineResponse_<ContainerAllocator> const> ConstPtr;

}; // struct determineResponse_

typedef ::determinant::determineResponse_<std::allocator<void> > determineResponse;

typedef boost::shared_ptr< ::determinant::determineResponse > determineResponsePtr;
typedef boost::shared_ptr< ::determinant::determineResponse const> determineResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::determinant::determineResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::determinant::determineResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::determinant::determineResponse_<ContainerAllocator1> & lhs, const ::determinant::determineResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::determinant::determineResponse_<ContainerAllocator1> & lhs, const ::determinant::determineResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace determinant

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::determinant::determineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::determinant::determineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::determinant::determineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::determinant::determineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::determinant::determineResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::determinant::determineResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::determinant::determineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "254fb2d8c4e08eff5dc6a560ed51dd52";
  }

  static const char* value(const ::determinant::determineResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x254fb2d8c4e08effULL;
  static const uint64_t static_value2 = 0x5dc6a560ed51dd52ULL;
};

template<class ContainerAllocator>
struct DataType< ::determinant::determineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "determinant/determineResponse";
  }

  static const char* value(const ::determinant::determineResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::determinant::determineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 result\n"
;
  }

  static const char* value(const ::determinant::determineResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::determinant::determineResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct determineResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::determinant::determineResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::determinant::determineResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<double>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETERMINANT_MESSAGE_DETERMINERESPONSE_H
