// Generated by gencpp from file determinant/Determinant_msg.msg
// DO NOT EDIT!


#ifndef DETERMINANT_MESSAGE_DETERMINANT_MSG_H
#define DETERMINANT_MESSAGE_DETERMINANT_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace determinant
{
template <class ContainerAllocator>
struct Determinant_msg_
{
  typedef Determinant_msg_<ContainerAllocator> Type;

  Determinant_msg_()
    : result(0.0)  {
    }
  Determinant_msg_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef double _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::determinant::Determinant_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::determinant::Determinant_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Determinant_msg_

typedef ::determinant::Determinant_msg_<std::allocator<void> > Determinant_msg;

typedef boost::shared_ptr< ::determinant::Determinant_msg > Determinant_msgPtr;
typedef boost::shared_ptr< ::determinant::Determinant_msg const> Determinant_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::determinant::Determinant_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::determinant::Determinant_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::determinant::Determinant_msg_<ContainerAllocator1> & lhs, const ::determinant::Determinant_msg_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::determinant::Determinant_msg_<ContainerAllocator1> & lhs, const ::determinant::Determinant_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace determinant

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::determinant::Determinant_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::determinant::Determinant_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::determinant::Determinant_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::determinant::Determinant_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::determinant::Determinant_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::determinant::Determinant_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::determinant::Determinant_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "254fb2d8c4e08eff5dc6a560ed51dd52";
  }

  static const char* value(const ::determinant::Determinant_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x254fb2d8c4e08effULL;
  static const uint64_t static_value2 = 0x5dc6a560ed51dd52ULL;
};

template<class ContainerAllocator>
struct DataType< ::determinant::Determinant_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "determinant/Determinant_msg";
  }

  static const char* value(const ::determinant::Determinant_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::determinant::Determinant_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 result\n"
;
  }

  static const char* value(const ::determinant::Determinant_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::determinant::Determinant_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Determinant_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::determinant::Determinant_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::determinant::Determinant_msg_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<double>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETERMINANT_MESSAGE_DETERMINANT_MSG_H
